In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from matplotlib import style
style.use('ggplot')

import warnings
warnings.filterwarnings('ignore')



In [17]:
df = pd.read_csv('salaries.csv')


In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   company                16 non-null     object
 1   job                    16 non-null     object
 2   degree                 16 non-null     object
 3   salary_more_then_100k  16 non-null     int64 
dtypes: int64(1), object(3)
memory usage: 644.0+ bytes


In [21]:
from sklearn.preprocessing import OrdinalEncoder
Encoder = OrdinalEncoder()
df[['company','job','degree']]=Encoder.fit_transform(df[['company','job','degree']])

# x = df[['company','job','degree']]
original_data = Encoder.fit_transform(df[['company','job','degree']])


In [23]:
df


company  job  degree  salary_more_then_100k
0       2.0  2.0     0.0                      0
1       2.0  2.0     1.0                      0
2       2.0  0.0     0.0                      1
3       2.0  0.0     1.0                      1
4       2.0  1.0     0.0                      0
5       2.0  1.0     1.0                      1
6       0.0  2.0     1.0                      0
7       0.0  1.0     0.0                      0
8       0.0  0.0     0.0                      0
9       0.0  0.0     1.0                      1
10      1.0  2.0     0.0                      1
11      1.0  2.0     1.0                      1
12      1.0  0.0     0.0                      1
13      1.0  0.0     1.0                      1
14      1.0  1.0     0.0                      1
15      1.0  1.0     1.0                      1

In [33]:
x = df[['company','job','degree']].values

In [35]:
Y =df[['salary_more_then_100k']].values

In [287]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test  =train_test_split(original_data,Y,test_size=0.4,random_state=5)

In [289]:
x_train

array([[2., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [2., 2., 0.],
       [1., 0., 0.],
       [0., 2., 1.],
       [1., 0., 1.],
       [1., 1., 0.],
       [2., 0., 1.]])

In [291]:
y_train

array([[0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1]], dtype=int64)

In [735]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [737]:
lr.fit(x_train,y_train)

LogisticRegression()

In [739]:
lr.predict(x_test)

array([1, 0, 0, 1, 0, 1, 0], dtype=int64)

In [741]:
x_test

array([[2., 1., 1.],
       [2., 2., 1.],
       [0., 1., 0.],
       [2., 0., 0.],
       [1., 2., 0.],
       [1., 1., 1.],
       [1., 2., 1.]])

In [743]:
lr.score(x_test,y_test)

0.7142857142857143

In [956]:
x_train,x_test,y_train,y_test  = train_test_split(original_data,Y,test_size=0.5,random_state=5)

In [968]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [970]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [972]:
knn.score(x_test,y_test)

0.75

In [974]:
knn.predict([[7.4,3.8,4.5]])

array([0], dtype=int64)

In [976]:
pred_train = lr.predict(x_train)
pred_test  = lr.predict(x_test)

from sklearn.metrics import r2_score
print('Training Set Score : ', r2_score(y_train, pred_train))
print('Testing Set Score  : ', r2_score(y_test, pred_test))

Training Set Score :  -0.06666666666666665
Testing Set Score  :  -0.06666666666666665
